Repository zantec/yarg-app, pull requests merged in 2019-03, with the labels that each got.

#8 updated README
  _CONTRIBUTING.md
  _README.md
  ios/yarg.xcodeproj/project.pbxproj
  ios/yarg/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/yarg/Info.plist
Labels: review

#19 Feat/gold
  yarg/.expo/packager-info.json
  yarg/.gitignore
  yarg/App.js
  yarg/babel.config.js
  yarg/components/ARView.js
  yarg/components/Gold.js
  yarg/components/Map.js
  yarg/navigation/MainTabNavigator.js
  yarg/package-lock.json
  yarg/package.json
  yarg/screens/ARScreen.js
  yarg/screens/HomeScreen.js
  yarg/screens/LinksScreen.js
  yarg/screens/MapScreen.js
  yarg/screens/SettingsScreen.js
Labels: review

#20 Should Be Able to Login
  yarg/App.js
  yarg/components/Login.js
  yarg/components/Map.js
  yarg/navigation/MainTabNavigator.js
  yarg/package-lock.json
  yarg/screens/LoginScreen.js
Labels: client, review

#25 Feat/profile
  yarg/.expo/packager-info.json
  yarg/.expo/settings.json
  yarg/components/StyledText.js
  yarg/components/profile/Inventory.js
  yarg/components/profile/RiddlesTreasures.js
  yarg/components/profile/Stats.js
  yarg/navigation/AppNavigator.js
  yarg/navigation/MainTabNavigator.js
  yarg/navigation/ProfileNavigator.js
  yarg/screens/MapScreen.js
  yarg/screens/ProfileScreen.js
Labels: client, review

#27 Map - Time Increase
  yarg/components/Map.js
Labels: client, review

#28 made leaderboard component
  yarg/components/LeaderBoard.js
Labels: review

#30 Feat/ar
  yarg/.expo/packager-info.json
  yarg/.expo/settings.json
  yarg/.gitignore
  yarg/App.js
  yarg/components/ARView.js
  yarg/components/Map.js
  yarg/components/RiddleModal.js
  yarg/screens/ARScreen.js
  yarg/screens/MapScreen.js
Labels: client, review

#31 should add modal
  yarg/components/Map.js
Labels: client, review

#32 Feat/ar
  yarg/App.js
  yarg/components/ARView.js
  yarg/components/Map.js
  yarg/components/RiddleModal.js
  yarg/navigation/MainTabNavigator.js
  yarg/package.json
  yarg/screens/ARScreen.js
  yarg/screens/MapScreen.js
Labels: client, review

#33 Should Be Able To Add Riddle/Treasure To User's Current GeoLocation
  yarg/components/Map.js
Labels: client, review

#37 Able To See Currently Placed Riddles And Treasures
  yarg/components/Map.js
  yarg/components/profile/RiddlesTreasures.js
Labels: client, review

#38 Able To See User Inventory
  yarg/components/Map.js
  yarg/components/profile/Inventory.js
Labels: client, review

#42 Rankings Component Fully Functional
  yarg/components/LeaderBoard.js
  yarg/navigation/ProfileNavigator.js
Labels: client, review

#44 New Icon
  yarg/navigation/ProfileNavigator.js
  yarg/package.json
Labels: client, review

#45 Feat/ar
  yarg/.expo/packager-info.json
  yarg/.gitignore
  yarg/App.js
  yarg/components/ARView.js
  yarg/components/LeaderBoard.js
  yarg/components/Map.js
  yarg/components/profile/Inventory.js
  yarg/components/profile/RiddlesTreasures.js
  yarg/package.json
  yarg/screens/ARScreen.js
  yarg/screens/MapScreen.js
Labels: client, review

#46 User Has Some Stats Now
  yarg/components/profile/Stats.js
  yarg/package.json
Labels: client, review

#51 Leaderbpard Component Functional
  yarg/components/LeaderBoard.js
  yarg/components/profile/Stats.js
Labels: client, review

#53 Able To Press Username and See Stats
  yarg/assets/fonts/Treamd.ttf
  yarg/components/LeaderBoard.js
Labels: client, enhancement, review

#54 3D scroll object in AR
  yarg/.expo/packager-info.json
  yarg/.expo/settings.json
  yarg/app.json
  yarg/assets/3D/scroll/14059PirateTreasuremapScroll_diffuse.jpg
  yarg/assets/3D/scroll/14059_Pirate_Treasure_map_Scroll_v1_L1.mtl
  yarg/assets/3D/scroll/14059_Pirate_Treasure_map_Scroll_v1_L1.obj
  yarg/components/ARView.js
  yarg/components/SketchFlag.js
  yarg/metro.config.js
  yarg/screens/ARScreen.js
Labels: review

#55 Riddle Board Implemented
  yarg/components/RiddleModal.js
  yarg/components/profile/Stats.js
Labels: client, review

#56 Feat/flag
  yarg/.expo/packager-info.json
  yarg/App.js
  yarg/components/LeaderBoard.js
  yarg/components/Map.js
  yarg/components/RiddleModal.js
  yarg/components/SketchFlag.js
  yarg/components/profile/Inventory.js
  yarg/components/profile/RiddlesTreasures.js
  yarg/components/profile/Stats.js
  yarg/package.json
  yarg/screens/ARScreen.js
Labels: client, enhancement, review

#58 tapping treasure sends patch request to update gold
  yarg/.expo/packager-info.json
  yarg/App.js
  yarg/components/ARView.js
  yarg/components/LeaderBoard.js
  yarg/components/Map.js
  yarg/components/RiddleModal.js
  yarg/components/SketchFlag.js
  yarg/navigation/ProfileNavigator.js
  yarg/screens/MapScreen.js
Labels: client, review

#60 Map UX Improvements
  yarg/components/LeaderBoard.js
  yarg/components/Map.js
Labels: client, enhancement, review

#62 current gold updates when treasure is buried
  yarg/components/Map.js
  yarg/package.json
  yarg/screens/MapScreen.js
Labels: review

#63 Inventory Riddles Show Up In Leaderboard
  yarg/App.js
  yarg/components/LeaderBoard.js
  yarg/components/profile/Stats.js
Labels: client, enhancement, review

#64 Fix
  yarg/components/LeaderBoard.js
Labels: review

#65 Map actual upgrade
  yarg/components/RiddleModal.js
Labels: review

#66 Small Visual Imrovements
  yarg/components/profile/RiddlesTreasures.js
  yarg/components/profile/Stats.js
Labels: client, review
